# Generated by Django 5.0 on 2026-05-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='latitude',
            field=models.FloatField(default=0.0, help_text='Zone GPS latitude. Update to real value.'),
        ),
        migrations.AddField(
            model_name='parkingzone',
            name='longitude',
            field=models.FloatField(default=0.0, help_text='Zone GPS longitude. Update to real value.'),
        ),
    ]
