# Generated by Django 5.0 on 2026-05-23 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_parkingzone_latitude_parkingzone_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emergency_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('fire', 'Fire Outbreak'), ('security', 'Security Threat'), ('missing', 'Missing Child'), ('traffic', 'Traffic Accident'), ('stampede', 'Crowd Stampede'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('dispatched', 'Dispatched'), ('on_scene', 'On Scene'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='reported', max_length=15)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_token', models.CharField(blank=True, max_length=64)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('responder_name', models.CharField(blank=True, max_length=100)),
                ('response_notes', models.TextField(blank=True)),
                ('response_time_minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('dispatched', 'Dispatched'), ('on_scene', 'On Scene'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], max_length=15)),
                ('note', models.TextField(blank=True)),
                ('updated_by', models.CharField(blank=True, default='System', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='App.emergencyreport')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
