# Generated by Django 5.0 on 2026-05-23 23:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_emergencyreport_emergencytimeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('lost_person', 'Lost Person'), ('found_person', 'Found Person'), ('lost_item', 'Lost Item'), ('found_item', 'Found Item')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_found/%Y/%m/')),
                ('location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('found', 'Found'), ('claimed', 'Claimed'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', max_length=15)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('item_type', models.CharField(blank=True, choices=[('phone', 'Phone'), ('bag', 'Bag/Wallet'), ('id_card', 'ID Card'), ('keys', 'Keys'), ('book', 'Book'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('jewelry', 'Jewelry'), ('documents', 'Documents'), ('other', 'Other')], max_length=20)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
