# Generated by Django 5.0 on 2026-05-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_lostfoundreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfoundreport',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
