# Generated by Django 5.0 on 2026-05-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_lostfoundreport_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='auto_release_at',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='occupied_at',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='occupied_by',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='session_token',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='vehicle_plate',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Average confidence score of detection', null=True),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='detected_vehicles',
            field=models.PositiveIntegerField(default=0, help_text='Number of vehicles detected by YOLO'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='last_detection_at',
            field=models.DateTimeField(blank=True, help_text='Last time YOLO detection ran', null=True),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('blocked', 'Blocked')], default='available', max_length=10),
        ),
        migrations.DeleteModel(
            name='CheckInSession',
        ),
    ]
