# Generated by Django 5.0 on 2026-06-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_whatsapp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='saved_locations',
            field=models.TextField(default='{}'),
        ),
    ]
