# Generated by Django 5.0 on 2026-06-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_add_saved_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
