# Generated by Django 5.0 on 2026-06-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='rate_window_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='rate_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
